# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25.xci
# IP: The module: 'clk_wiz_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25.xci
# IP: The module: 'clk_wiz_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/dsdlab/friday/250_202/lab 8/Image_cryption/Image_cryption.srcs/sources_1/ip/clk_wiz_25/clk_wiz_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
