set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports z]
set_property PACKAGE_PIN F15 [get_ports clk]
set_property PACKAGE_PIN U9 [get_ports x]
set_property PACKAGE_PIN T8 [get_ports z]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN V10 [get_ports rst]
set_propety CLOCK_DEDICATED_ROUTE false[get_nets clk_IBUF]