# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/dsdlab/friday/250_202/lab3/project_3/project_3.cache/wt [current_project]
set_property parent.project_path D:/dsdlab/friday/250_202/lab3/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  D:/dsdlab/friday/250_202/lab1/lab1.srcs/sources_1/new/bcd_to_seven_seg.vhd
  D:/dsdlab/friday/250_202/lab3/project_3/project_3.srcs/sources_1/new/adder_4.vhd
  D:/dsdlab/friday/250_202/lab3/project_3/project_3.srcs/sources_1/new/bcd_adder.vhd
}
read_xdc D:/dsdlab/friday/250_202/lab3/project_3/project_3.srcs/constrs_1/new/bcd_pin_list.xdc
set_property used_in_implementation false [get_files D:/dsdlab/friday/250_202/lab3/project_3/project_3.srcs/constrs_1/new/bcd_pin_list.xdc]

synth_design -top bcd_adder -part xc7a100tcsg324-1
write_checkpoint -noxdef bcd_adder.dcp
catch { report_utilization -file bcd_adder_utilization_synth.rpt -pb bcd_adder_utilization_synth.pb }
