set_property PACKAGE_PIN R6 [get_ports {data_in[3]}]
set_property PACKAGE_PIN R7 [get_ports {data_in[2]}]
set_property PACKAGE_PIN U8 [get_ports {data_in[1]}]
set_property PACKAGE_PIN U9 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]
set_property PACKAGE_PIN U4 [get_ports load]
set_property PACKAGE_PIN P4 [get_ports up]
set_property PACKAGE_PIN V2 [get_ports clear]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN T8 [get_ports tc]
set_property IOSTANDARD LVCMOS33 [get_ports clear]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports load]
set_property IOSTANDARD LVCMOS33 [get_ports tc]
set_property IOSTANDARD LVCMOS33 [get_ports up]







set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_enab[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_out[0]}]
set_property PACKAGE_PIN M1 [get_ports {bit_enab[7]}]
set_property PACKAGE_PIN L1 [get_ports {bit_enab[6]}]
set_property PACKAGE_PIN N4 [get_ports {bit_enab[5]}]
set_property PACKAGE_PIN N2 [get_ports {bit_enab[4]}]
set_property PACKAGE_PIN N5 [get_ports {bit_enab[3]}]
set_property PACKAGE_PIN M3 [get_ports {bit_enab[2]}]
set_property PACKAGE_PIN M6 [get_ports {bit_enab[1]}]
set_property PACKAGE_PIN N6 [get_ports {bit_enab[0]}]
set_property PACKAGE_PIN L3 [get_ports {bit_out[7]}]
set_property PACKAGE_PIN N1 [get_ports {bit_out[6]}]
set_property PACKAGE_PIN L5 [get_ports {bit_out[5]}]
set_property PACKAGE_PIN L4 [get_ports {bit_out[4]}]
set_property PACKAGE_PIN K3 [get_ports {bit_out[3]}]
set_property PACKAGE_PIN M2 [get_ports {bit_out[2]}]
set_property PACKAGE_PIN L6 [get_ports {bit_out[1]}]
set_property PACKAGE_PIN M4 [get_ports {bit_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {data_lsb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lsb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lsb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_lsb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_msb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_msb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_msb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_msb[0]}]
set_property PACKAGE_PIN R6 [get_ports {data_lsb[3]}]
set_property PACKAGE_PIN R7 [get_ports {data_lsb[2]}]
set_property PACKAGE_PIN U8 [get_ports {data_lsb[1]}]
set_property PACKAGE_PIN U9 [get_ports {data_lsb[0]}]
set_property PACKAGE_PIN V5 [get_ports {data_msb[3]}]
set_property PACKAGE_PIN V6 [get_ports {data_msb[2]}]
set_property PACKAGE_PIN V7 [get_ports {data_msb[1]}]
set_property PACKAGE_PIN R5 [get_ports {data_msb[0]}]
