set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports resetc]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[0]}]

set_property MARK_DEBUG false [get_nets {dout_OBUF[4]}]
set_property MARK_DEBUG false [get_nets {dout_OBUF[7]}]
set_property MARK_DEBUG false [get_nets {dout_OBUF[5]}]
set_property MARK_DEBUG false [get_nets {dout_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {cntr0[0]}]
set_property MARK_DEBUG true [get_nets {cntr0[1]}]
set_property MARK_DEBUG true [get_nets {cntr0[2]}]
set_property MARK_DEBUG true [get_nets {cntr0[3]}]
set_property MARK_DEBUG true [get_nets thresh0]
create_debug_core u_ila_0_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
connect_debug_port u_ila_0_0/clk [get_nets [list clkin_IBUF]]
set_property port_width 4 [get_debug_ports u_ila_0_0/probe0]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {component1/Q[0]} {component1/Q[1]} {component1/Q[2]} {component1/Q[3]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe1]
connect_debug_port u_ila_0_0/probe1 [get_nets [list component1/THRESH0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clkin_IBUF]
