# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/dsdlab/friday/250_202/lab5/lab5_1/lab5_1.cache/wt [current_project]
set_property parent.project_path D:/dsdlab/friday/250_202/lab5/lab5_1/lab5_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  D:/dsdlab/friday/250_202/lab5/lab5_1/lab5_1.srcs/sources_1/new/package_ec.vhd
  D:/dsdlab/friday/250_202/lab5/lab5_1/lab5_1.srcs/sources_1/new/int2vec.vhd
}
synth_design -top int2vectest -part xc7a100tcsg324-1
write_checkpoint -noxdef int2vectest.dcp
catch { report_utilization -file int2vectest_utilization_synth.rpt -pb int2vectest_utilization_synth.pb }
