# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/dsdlab/friday/250_202/lab5/barrel_shifter/barrel_shifter.cache/wt [current_project]
set_property parent.project_path D:/dsdlab/friday/250_202/lab5/barrel_shifter/barrel_shifter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib D:/dsdlab/friday/250_202/lab5/barrel_shifter/barrel_shifter.srcs/sources_1/new/bshifter.vhd
read_xdc D:/dsdlab/friday/250_202/lab5/barrel_shifter/barrel_shifter.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files D:/dsdlab/friday/250_202/lab5/barrel_shifter/barrel_shifter.srcs/constrs_1/new/const.xdc]

synth_design -top bshifter -part xc7a100tcsg324-1
write_checkpoint -noxdef bshifter.dcp
catch { report_utilization -file bshifter_utilization_synth.rpt -pb bshifter_utilization_synth.pb }
